# Generated by Django 2.2 on 2019-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190426_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание категории'),
        ),
    ]
